import { useState } from 'react';
import { motion } from 'motion/react';
import { 
  Zap, 
  ShieldCheck, 
  Sparkles, 
  Smartphone, 
  Download, 
  ChevronDown, 
  ChevronUp, 
  HelpCircle,
  Eye,
  Link,
  Phone,
  Wifi,
  QrCode,
  Layers,
  ArrowRight,
  MonitorCheck,
  CheckCircle,
  Files,
  Cpu,
  Camera,
  UserX
} from 'lucide-react';
import QRGenerator from '../components/QRGenerator';
import SEOHead from '../components/SEOHead';
import { FAQItem, PageId } from '../types';

interface HomeProps {
  onNavigate: (page: PageId) => void;
}

export default function Home({ onNavigate }: HomeProps) {
  // FAQ toggling states (individual index expansion)
  const [expandedFAQ, setExpandedFAQ] = useState<number | null>(0);

  const heroScrollToGenerator = () => {
    const el = document.getElementById('generator-section');
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const faqItems: FAQItem[] = [
    {
      question: "Are these QR codes completely free to use?",
      answer: "Yes, 100% free! Every QR code you generate using Quick QR Code is completely free of charge, with no subscriptions, membership trials, watermarks, or artificial scan restrictions."
    },
    {
      question: "Do generated static QR codes ever expire?",
      answer: "No. The static QR codes generated by our tool will never expire. Because they store your data directly into the custom geometric pattern (pixels) of the code itself, they operate permanently as long as the content (e.g., website link) remains active."
    },
    {
      question: "Is there any limit to the number of scans my QR codes can get?",
      answer: "No, there is absolutely no scan limit. Since the generated maps are static, they can be scanned an infinite number of times by any device, with no platform costs."
    },
    {
      question: "Can I use these QR codes for commercial projects and marketing?",
      answer: "Absolutely! You are fully authorized to print, distribute, and embed the generated QR codes in commercial flyers, catalogs, shop signage, t-shirts, packaging material, or digital channels without paying any licensing royalties."
    },
    {
      question: "Is my personal data or credentials stored on your servers?",
      answer: "No, never. Unlike other tools, Quick QR Code performs all geometric drawings locally inside your web browser. This means your private wifi passwords, cell numbers, names, and email strings never leave your device or touch our computing servers."
    },
    {
      question: "What does the Error Correction Level (ECC) selector do?",
      answer: "Error Correction allows QR codes to remain readable even if they are scratched, dirty, distorted, or printed on uneven surfaces. Selecting 'High' adds extra redundancy so the code handles up to 30% visual damage, but increases the visual complexity of the pattern."
    },
    {
      question: "Can I customize the primary colors of my QR code?",
      answer: "Yes, our customizer lets you pick any hex colors for the dark blocks (foreground) and light tiles (background). Just ensure there is enough visual contrast (high color-difference) so smartphone scanners can parse the pattern."
    },
    {
      question: "Why isn't my mobile camera scanning my generated QR code?",
      answer: "This is usually caused by low color contrast (the dark blocks being too light relative to the background), insufficient margins around the code, or scanning from a dirty camera lens. Check that your foreground color is robustly dark (such as navy or black) and the background is light."
    },
    {
      question: "What is the key difference between static and dynamic QR codes?",
      answer: "Static QR codes encode data directly inside the matrix — which makes them secure and unalterable. Dynamic QR codes encode a short redirection URL that points to a server database, which allows you to change the destination website later but introduces server latency and tracking risks."
    },
    {
      question: "How do I choose the right size for my QR code download?",
      answer: "Choose 'Small' (250px) for websites or email footers, 'Medium' (400px) for standard business cards or menus, and 'Large' (650px) for large poster flyers, signage, or merchandise printing where pixels must remain ultra-sharp."
    },
    {
      question: "How do I scan a QR code online using my computer or mobile device?",
      answer: "You can use our secure online QR Code Scanner! Simply navigate to the 'QR Scanner' page from our top menu. You can then grant temporary camera permission to scan physical codes in real-time, or drag and drop any screenshot or image file to extract details immediately."
    },
    {
      question: "Is it safe to scan unknown QR codes in public places?",
      answer: "Just like clicking random email links, you should scan QR codes cautiously. We recommend using our client-side QR Scanner tool because it clearly displays the decoded plain text or URL destination first, letting you inspect the safety of links before clicking to visit them."
    },
    {
      question: "Can your QR Scanner read codes from my smartphone screenshots?",
      answer: "Yes, absolutely! Our tool contains a dedicated 'Upload Image File' decoding feature. Simply take a screenshot of any QR code you find online, upload it to our scanner tool, and our local browser decoder will parse the information in milliseconds."
    },
    {
      question: "Why does my browser request camera permissions on the scanner tab?",
      answer: "In order to analyze physical barcodes in real-time, your browser requires secure, sandboxed access to your device camera stream. This connection is 100% local inside your web browser—absolutely no images, videos, or feeds are ever uploaded to external cloud servers."
    },
    {
      question: "Does this QR toolkit work across both iOS iPhones and Android devices?",
      answer: "Yes! Both the QR Generator and the QR Scanner are fully cross-compatible and mobile-optimized. The live scanner runs seamlessly on Safari (iOS), Google Chrome (Android/Windows), Mozilla Firefox, and Microsoft Edge with no App Store downloads required."
    },
    {
      question: "Why is my QR code not scanning even though the colors are black and white?",
      answer: "If contrast is high, ensure the camera is steady and well-focused. Keep the code fully within the scan frame. Sometimes, if the code is exceptionally small or has complex data, you may need to zoom in slightly or clean your device camera lens to ensure clear recognition."
    }
  ];

  // Prepare standard Google Structured Data schemas
  const webSiteSchema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": "Quick QR Code",
    "url": "https://quickqrcode.pages.dev",
    "description": "Generate QR Codes Instantly for Free. Responsive, secure, browser-based QR Code Generator."
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqItems.map(item => ({
      "@type": "Question",
      "name": item.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": item.answer
      }
    }))
  };

  return (
    <div className="bg-slate-50 min-h-screen text-slate-800" id="home-view">
      <SEOHead 
        title="Free QR Code Generator Online - Instant QR Code Generator Free"
        description="Need a free qr code generator? Use our quick, instant qr code generator online to create custom codes. Free, private, and secure with no expiration limits."
        keywords="qr code generator, free qr code generator, qr code generator free, adobe qr code generator, canva qr code generator, google qr code generator, qr code generator for location, qr code generator online, quick qr code generator, instant qr code generator"
        path=""
        schemas={[webSiteSchema, faqSchema]}
      />

      {/* 1. HERO SECTION */}
      <section className="relative overflow-hidden bg-white pt-20 pb-20 border-b border-slate-100" id="hero-section">
        <div className="absolute inset-0 bg-radial-gradient from-sky-50/40 via-white to-white pointer-events-none" />
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative z-10 text-center">
          
          {/* Tagline Badge */}
          <div className="inline-flex items-center gap-2 rounded-full bg-indigo-50/50 px-3.5 py-1.5 text-xs font-semibold text-indigo-950 mb-6 border border-indigo-100 shadow-sm animate-fade-in" id="hero-badge">
            <Sparkles className="h-4 w-4 text-indigo-600 fill-indigo-200" />
            <span>Generate QR Codes Instantly for Free</span>
          </div>

          <h2 className="font-display text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-slate-900 max-w-4xl mx-auto leading-tight sm:leading-none">
            Free QR Code <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-violet-600">Generator Online</span>
          </h2>
          <p className="mt-6 text-base sm:text-lg text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Create completely custom, high-resolution QR codes in seconds. Absolutely free of charge, with instant downloads, zero tracking, and zero expiration limits. All process takes place 100% safely inside your web browser.
          </p>

          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4" id="hero-ctas">
            <button
              onClick={heroScrollToGenerator}
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-7 py-4 text-base font-bold text-white shadow-xl hover:shadow-indigo-100/50 transition-all duration-300 hover:bg-indigo-700 cursor-pointer"
              id="btn-hero-generate"
            >
              Generate QR Code
              <Zap className="h-5 w-5 text-indigo-200 fill-indigo-200" />
            </button>
            <button
              onClick={() => {
                onNavigate('scanner');
                window.scrollTo({ top:0, behavior:'instant'});
              }}
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-7 py-4 text-base font-semibold text-slate-700 hover:bg-slate-50 transition shadow-xs hover:border-slate-300 cursor-pointer"
              id="btn-hero-scanner"
            >
              <Camera className="h-5 w-5 text-indigo-500 shrink-0" />
              Scan QR Code Online
            </button>
          </div>

          {/* Core Trust Indicators */}
          <div className="mt-12 flex flex-wrap justify-center items-center gap-x-8 gap-y-3 text-slate-400 text-xs font-mono" id="hero-trust-metrics">
            <span className="flex items-center gap-1.5 font-medium"><ShieldCheck className="h-4 w-4 text-emerald-500" /> No Log-In Required</span>
            <span className="flex items-center gap-1.5 font-medium"><Zap className="h-4 w-4 text-amber-500" /> Instant Processing</span>
            <span className="flex items-center gap-1.5 font-medium"><MonitorCheck className="h-4 w-4 text-blue-500" /> No Data Saved</span>
          </div>
        </div>
      </section>

      {/* 2. QR GENERATOR TOOL BOX SECTION */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 mx-auto max-w-7xl" id="generator-section">

        <div className="text-center mb-10">
          <h3 className="font-display text-2xl sm:text-3xl font-extrabold text-slate-900">
            Generate Custom QR Codes
          </h3>
          <p className="text-slate-500 text-sm mt-2">
            Configure your data, design elements, and download instantly.
          </p>
        </div>
        
        {/* Core Generator component */}
        <QRGenerator />
      </section>

      {/* 3. KEY FEATURES SECTION */}
      <section className="bg-white py-16 border-t border-b border-slate-100" id="features-section">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <h3 className="font-display text-2xl sm:text-3xl font-extrabold text-slate-900">
              Why Choose Quick QR Code?
            </h3>
            <p className="text-slate-500 mt-2 text-sm leading-relaxed">
              We engineered a secure, client-first alternative to bloated corporate QR generators.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8" id="features-grid">
            {/* Feat 1: QR Code Generator */}
            <div className="p-6 rounded-2xl bg-white border border-slate-100 hover:scale-[1.02] hover:shadow-lg hover:shadow-indigo-50/40 transition-all duration-300 cursor-pointer flex flex-col justify-between" onClick={() => {
              const element = document.getElementById('generator-section');
              if (element) element.scrollIntoView({ behavior: 'smooth' });
            }}>
              <div>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 border border-indigo-100/60 mb-4">
                  <QrCode className="h-6 w-6 font-semibold animate-pulse" />
                </div>
                <h4 className="font-display text-base font-bold text-slate-900">QR Code Generator</h4>
                <p className="mt-2 text-xs text-slate-500 leading-relaxed">
                  Design high-definition QR codes for websites, WiFi SSID networks, text blocks, telephone numbers, and email messages with full style customized presets.
                </p>
              </div>
              <div className="mt-4 flex items-center gap-1 text-[11px] font-bold text-indigo-600">
                <span>Configure & Generate</span>
                <ArrowRight className="h-3 w-3" />
              </div>
            </div>

            {/* Feat 2: QR Code Scanner */}
            <div className="p-6 rounded-2xl bg-white border border-slate-100 hover:scale-[1.02] hover:shadow-lg hover:shadow-indigo-50/40 transition-all duration-300 cursor-pointer flex flex-col justify-between" onClick={() => {
              onNavigate('scanner');
              window.scrollTo({ top: 0, behavior: 'instant' });
            }}>
              <div>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-50 text-amber-600 border border-amber-100/60 mb-4">
                  <Camera className="h-6 w-6 font-semibold" />
                </div>
                <h4 className="font-display text-base font-bold text-slate-900">QR Code Scanner</h4>
                <p className="mt-2 text-xs text-slate-500 leading-relaxed">
                  Decode QR codes online using your front/back device camera or instantly upload screenshots and image files (PNG, JPG, WEBP).
                </p>
              </div>
              <div className="mt-4 flex items-center gap-1 text-[11px] font-bold text-amber-600">
                <span>Open Scanner Tool</span>
                <ArrowRight className="h-3 w-3" />
              </div>
            </div>

            {/* Feat 3: Secure & Private */}
            <div className="p-6 rounded-2xl bg-white border border-slate-100 hover:scale-[1.02] hover:shadow-lg hover:shadow-indigo-50/40 transition-all duration-300 flex flex-col justify-between">
              <div>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 border border-emerald-100/60 mb-4">
                  <ShieldCheck className="h-6 w-6 font-semibold" />
                </div>
                <h4 className="font-display text-base font-bold text-slate-900">Secure & Private</h4>
                <p className="mt-2 text-xs text-slate-500 leading-relaxed">
                  We process every vector calculation and image-scanning frame locally in your browser memory. Your sensitive keys and passwords never touch our cloud.
                </p>
              </div>
              <div className="mt-4 text-[10px] text-emerald-600 font-mono flex items-center gap-1">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                No data tracking
              </div>
            </div>

            {/* Feat 4: Mobile Friendly */}
            <div className="p-6 rounded-2xl bg-white border border-slate-100 hover:scale-[1.02] hover:shadow-lg hover:shadow-indigo-50/40 transition-all duration-300 flex flex-col justify-between">
              <div>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-purple-50 text-purple-600 border border-purple-100/60 mb-4">
                  <Smartphone className="h-6 w-6 font-semibold" />
                </div>
                <h4 className="font-display text-base font-bold text-slate-900">Mobile Friendly</h4>
                <p className="mt-2 text-xs text-slate-500 leading-relaxed">
                  Both our generator and mobile-ready camera scanner are optimized for rapid, finger-friendly taps, smooth sliders, and native screen boundaries.
                </p>
              </div>
              <div className="mt-4 text-[10px] text-purple-600 font-mono flex items-center gap-1">
                <span className="h-1.5 w-1.5 rounded-full bg-purple-500" />
                Responsive layouts
              </div>
            </div>

            {/* Feat 5: No Registration Required */}
            <div className="p-6 rounded-2xl bg-white border border-slate-100 hover:scale-[1.02] hover:shadow-lg hover:shadow-indigo-50/40 transition-all duration-300 flex flex-col justify-between md:col-span-2 lg:col-span-1">
              <div>
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-pink-50 text-pink-600 border border-pink-100/60 mb-4">
                  <UserX className="h-6 w-6 font-semibold" />
                </div>
                <h4 className="font-display text-base font-bold text-slate-900">No Registration Required</h4>
                <p className="mt-2 text-xs text-slate-500 leading-relaxed">
                  Avoid paying costly subscription tiers or supplying your email address. Create and read infinite barcodes with no subscription walls or watermarks.
                </p>
              </div>
              <div className="mt-4 text-[10px] text-pink-600 font-mono flex items-center gap-1">
                <span className="h-1.5 w-1.5 rounded-full bg-pink-500" />
                100% Free Forever
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 4. HOW IT WORKS SECTION */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 mx-auto max-w-7xl" id="how-it-works">
        <div className="text-center max-w-3xl mx-auto mb-14">
          <h3 className="font-display text-2xl sm:text-3xl font-extrabold text-slate-900">
            Generate in 3 Simple Steps
          </h3>
          <p className="text-slate-500 mt-2 text-sm">
            Our clean browser technology streamlines creation without complexity.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative" id="how-it-works-grid">
          {/* Connector line */}
          <div className="hidden md:block absolute top-12 left-1/6 right-1/6 h-0.5 bg-slate-200 z-0" />

          {/* Step 1 */}
          <div className="flex flex-col items-center text-center relative z-10 group" id="step-one">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-indigo-600 text-white font-display text-xl font-bold shadow-md group-hover:bg-indigo-700 transition-all duration-300 shadow-indigo-100/50">
              1
            </div>
            <h4 className="font-display text-base font-bold text-slate-900 mt-5">Enter Content</h4>
            <p className="mt-2 text-xs text-slate-500 max-w-xs leading-relaxed">
              Select your data format (website Link, text blocks, WiFi name & password, or contact email) and type down details.
            </p>
          </div>

          {/* Step 2 */}
          <div className="flex flex-col items-center text-center relative z-10 group" id="step-two">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-indigo-600 text-white font-display text-xl font-bold shadow-md group-hover:bg-indigo-700 transition-all duration-300 shadow-indigo-100/50">
              2
            </div>
            <h4 className="font-display text-base font-bold text-slate-900 mt-5">Configure Design</h4>
            <p className="mt-2 text-xs text-slate-500 max-w-xs leading-relaxed">
              Tweak output sizes, safety margin limits, background & foreground colors, and pick optimal error-correction values.
            </p>
          </div>

          {/* Step 3 */}
          <div className="flex flex-col items-center text-center relative z-10 group" id="step-three">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-indigo-600 text-white font-display text-xl font-bold shadow-md group-hover:bg-indigo-700 transition-all duration-300 shadow-indigo-100/50">
              3
            </div>
            <h4 className="font-display text-base font-bold text-slate-900 mt-5">Download instantly</h4>
            <p className="mt-2 text-xs text-slate-500 max-w-xs leading-relaxed">
              Download your custom QR code immediately as a pixel-perfect high-quality PNG. It is completely ready for print and web integration!
            </p>
          </div>
        </div>
      </section>

      {/* 5. USE CASES SECTION */}
      <section className="bg-slate-900 text-white py-16 px-4 sm:px-6 lg:px-8" id="use-cases-section">
        <div className="mx-auto max-w-7xl">
          <div className="flex flex-col md:flex-row md:items-end md:justify-between border-b border-slate-800 pb-10 mb-12">
            <div>
              <span className="text-xs font-mono font-bold tracking-wider text-indigo-400 uppercase">Utility Blueprint</span>
              <h3 className="font-display text-2xl sm:text-3xl font-extrabold text-white mt-1">
                Practical QR Use Cases
              </h3>
            </div>
            <p className="text-slate-400 text-sm max-w-md mt-4 md:mt-0 leading-relaxed">
              Incorporate scannable shortcuts in creative pathways to enhance reader accessibility.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6" id="use-cases-grid">
            {/* Case 1 */}
            <div className="p-5 rounded-xl bg-slate-950/60 border border-slate-800 flex flex-col justify-between">
              <div>
                <QrCode className="h-6 w-6 text-indigo-400 mb-4" />
                <h4 className="font-display text-sm font-bold text-white">Business Cards</h4>
              </div>
              <p className="text-xs text-slate-400 mt-3 leading-relaxed">
                Add contact or phone links directly to your paper business cards for hassle-free dial numbers save.
              </p>
            </div>

            {/* Case 2 */}
            <div className="p-5 rounded-xl bg-slate-950/60 border border-slate-800 flex flex-col justify-between">
              <div>
                <Link className="h-6 w-6 text-emerald-400 mb-4" />
                <h4 className="font-display text-sm font-bold text-white">Websites</h4>
              </div>
              <p className="text-xs text-slate-400 mt-3 leading-relaxed">
                Bridge desktop pages directly to mobile landing stores or app store download links.
              </p>
            </div>

            {/* Case 3 */}
            <div className="p-5 rounded-xl bg-slate-950/60 border border-slate-800 flex flex-col justify-between">
              <div>
                <Sparkles className="h-6 w-6 text-purple-400 mb-4" />
                <h4 className="font-display text-sm font-bold text-white">Social Media</h4>
              </div>
              <p className="text-xs text-slate-400 mt-3 leading-relaxed">
                Redirect offline restaurant menus or retail packages straight to your brand social networks.
              </p>
            </div>

            {/* Case 4 */}
            <div className="p-5 rounded-xl bg-slate-950/60 border border-slate-800 flex flex-col justify-between">
              <div>
                <Wifi className="h-6 w-6 text-amber-400 mb-4" />
                <h4 className="font-display text-sm font-bold text-white">WiFi Sharing</h4>
              </div>
              <p className="text-xs text-slate-400 mt-3 leading-relaxed">
                Let restaurant guests or home visitors easily sign on to your encrypted security routers with a fast snap.
              </p>
            </div>

            {/* Case 5 */}
            <div className="p-5 rounded-xl bg-slate-950/60 border border-slate-800 flex flex-col justify-between">
              <div>
                <Phone className="h-6 w-6 text-rose-400 mb-4" />
                <h4 className="font-display text-sm font-bold text-white">Contact Cards</h4>
              </div>
              <p className="text-xs text-slate-400 mt-3 leading-relaxed">
                Formulate mail links, SMS shortkeys, or dial patterns to automate lead bookings instantly.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* 6. FAQ ACCORDION SECTION (10 ITEMS) */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 mx-auto max-w-4xl" id="faq-section">
        <div className="text-center mb-12">
          <h3 className="font-display text-2xl sm:text-3xl font-extrabold text-slate-900">
            Frequently Asked Questions
          </h3>
          <p className="text-slate-500 mt-2 text-sm">
            Everything you need to know about setting up and using QR codes.
          </p>
        </div>

        <div className="space-y-3.5" id="faq-accordion-holder">
          {faqItems.map((item, idx) => {
            const isExpanded = expandedFAQ === idx;
            return (
              <div 
                key={idx} 
                className="bg-white border border-slate-100 rounded-xl overflow-hidden transition-all duration-200"
              >
                <button
                  type="button"
                  onClick={() => setExpandedFAQ(isExpanded ? null : idx)}
                  className="w-full flex items-center justify-between p-4.5 text-left text-sm font-semibold text-slate-900 hover:bg-slate-50/60 transition"
                  id={`btn-faq-trigger-${idx}`}
                >
                  <span className="flex items-center gap-2.5">
                    <HelpCircle className="h-4 w-4 text-slate-400 shrink-0" />
                    {item.question}
                  </span>
                  {isExpanded ? (
                    <ChevronUp className="h-4 w-4 text-slate-500 shrink-0" />
                  ) : (
                    <ChevronDown className="h-4 w-4 text-slate-500 shrink-0" />
                  )}
                </button>
                {isExpanded && (
                  <div className="px-4.5 pb-4 text-xs text-slate-500 leading-relaxed border-t border-slate-50 pt-3" id={`faq-answer-${idx}`}>
                    {item.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* 6.5 SEO CONTENT SECTION */}
      <section className="py-14 bg-indigo-50/30 border-t border-b border-indigo-100/50 animate-fade-in" id="seo-content-section">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 rounded-full bg-indigo-100/60 px-3 py-1 text-[10px] font-mono uppercase font-bold text-indigo-950 mb-6 border border-indigo-200/50">
            <Sparkles className="h-3.5 w-3.5 text-indigo-600 fill-indigo-200" />
            <span>Search Engine Optimization (SEO) Directory</span>
          </div>
          
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 text-left max-w-5xl mx-auto">
            {/* Column 1: QR Code Generator */}
            <div className="bg-white p-6.5 rounded-2xl border border-indigo-100/40 shadow-2xs">
              <h2 className="font-display text-lg font-extrabold text-slate-900 mb-3 flex items-center gap-2">
                <span className="text-xl">✨</span> The Ultimate Online QR Code Generator
              </h2>
              <p className="text-xs text-slate-600 leading-relaxed">
                Looking for a reliable <strong className="font-semibold text-slate-900">qr code generator</strong>? Quick QR Code is a professional, <strong className="font-semibold text-indigo-700">free qr code generator</strong> designed to create custom scannable vectors in seconds. Whether you need a <strong className="font-semibold text-slate-900">qr code generator free</strong> of watermarks or want to replace your <strong className="font-semibold text-slate-900">adobe qr code generator</strong> and <strong className="font-semibold text-slate-900">canva qr code generator</strong> subscriptions, our secure, browser-local tool is the perfect choice. This versatile <strong className="font-semibold text-slate-900">google qr code generator</strong> alternative lets you customize styles, logos, and error correction levels for high-quality printing. Easily construct credentials for URLs, WiFi networks, emails, or use our <strong className="font-semibold text-slate-900">qr code generator for location</strong> mapping. Operating completely as an advanced <strong className="font-semibold text-slate-900">qr code generator online</strong>, it offers a <strong className="font-semibold text-slate-900">quick qr code generator</strong> engine that performs all styling calculations locally inside your browser memory. Enjoy an <strong className="font-semibold text-slate-900">instant qr code generator</strong> experience with zero scan limits, zero tracking, and zero expiration. Generate your next custom barcode securely today!
              </p>
            </div>

            {/* Column 2: QR Code Scanner */}
            <div className="bg-white p-6.5 rounded-2xl border border-indigo-100/40 shadow-2xs">
              <h2 className="font-display text-lg font-extrabold text-slate-900 mb-3 flex items-center gap-2">
                <span className="text-xl">🔍</span> Instant, Secure Online QR Code Scanner
              </h2>
              <p className="text-xs text-slate-600 leading-relaxed">
                Need a fast and secure <strong className="font-semibold text-slate-900">qr code scanner</strong>? Quick QR Code provides an advanced <strong className="font-semibold text-indigo-700">qr code scanner online</strong> that decodes barcodes instantly using your device's camera or direct image uploads. Our completely <strong className="font-semibold text-slate-900">free qr code scanner</strong> works directly in your web browser with zero installation, serving as a reliable <strong className="font-semibold text-slate-900">qr code scanner from image</strong> files. Experience the convenience of an <strong className="font-semibold text-slate-900">online qr code scanner</strong> on any device, fully optimized as an ad-free <strong className="font-semibold text-slate-900">qr code scanner online free</strong>. Perfectly responsive, it acts as a lightweight <strong className="font-semibold text-slate-900">qr code scanner android</strong> and iOS tool, as well as a high-performance <strong className="font-semibold text-slate-900">qr code scanner PC</strong> desktop utility. Simply visit our <strong className="font-semibold text-slate-900">qr code scanner website</strong> with no need to download a heavy <strong className="font-semibold text-slate-900">qr code scanner app</strong>. Additionally, use it as a smart <strong className="font-semibold text-slate-900">qr code scanner for wifi password</strong> lookup or a generic <strong className="font-semibold text-slate-900">wifi qr code scanner</strong> to join wireless networks securely in seconds. Enjoy safe, client-side decoding!
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* 7. RELATED TOOLS SECTION */}
      <section className="bg-white py-16 border-t border-slate-100" id="related-tools-section">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <span className="text-[10px] font-mono font-semibold text-indigo-600 uppercase tracking-wider bg-indigo-50 px-2.5 py-1 rounded-full">Suite Expansion</span>
            <h3 className="font-display text-2xl font-extrabold text-slate-900 mt-2">
              Future Companion Utilities
            </h3>
            <p className="text-slate-500 text-sm mt-1">
              Coming soon! We are actively expanding our free slate of lightweight vector barcode tools.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6" id="related-tools-grid">
            
            {/* Companion Tool 1 */}
            <div className="p-5.5 rounded-2xl bg-slate-50 border border-slate-100/60 relative group overflow-hidden">
              <div className="absolute top-3 right-3 text-[9px] font-mono bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded-full font-bold">Planned</div>
              <Cpu className="h-6 w-6 text-indigo-500 mb-4" />
              <h4 className="font-display text-sm font-bold text-slate-800">Dynamic Key QR Portal</h4>
              <p className="text-xs text-slate-500 mt-2 leading-relaxed">
                Generate flexible shortlinks that let you modify target redirect pages at any point, with unified scannability indexes.
              </p>
              <div className="mt-4 inline-flex items-center gap-1 text-[10px] text-slate-400 font-semibold uppercase font-mono tracking-wider">
                Read development specs <ArrowRight className="h-3 w-3" />
              </div>
            </div>

            {/* Companion Tool 2 */}
            <div className="p-5.5 rounded-2xl bg-slate-50 border border-slate-100/60 relative group overflow-hidden">
              <div className="absolute top-3 right-3 text-[9px] font-mono bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded-full font-bold">Planned</div>
              <Files className="h-6 w-6 text-purple-500 mb-4" />
              <h4 className="font-display text-sm font-bold text-slate-800">Bulk Multi-QR Generator</h4>
              <p className="text-xs text-slate-500 mt-2 leading-relaxed">
                Upload comma-separated lines (CSVs) of spreadsheet data, names, and contact items to compile hundreds of PNG files simultaneously.
              </p>
              <div className="mt-4 inline-flex items-center gap-1 text-[10px] text-slate-400 font-semibold uppercase font-mono tracking-wider">
                Read development specs <ArrowRight className="h-3 w-3" />
              </div>
            </div>

            {/* Companion Tool 3 */}
            <div className="p-5.5 rounded-2xl bg-slate-50 border border-slate-100/60 relative group overflow-hidden">
              <div className="absolute top-3 right-3 text-[9px] font-mono bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded-full font-bold">In backlog</div>
              <Layers className="h-6 w-6 text-indigo-500 mb-4" />
              <h4 className="font-display text-sm font-bold text-slate-800">Universal Barcode Creator</h4>
              <p className="text-xs text-slate-500 mt-2 leading-relaxed">
                Create retail-ready UPC-A, EAN-13, and Code 128 barcodes directly in-browser using standard vector templates.
              </p>
              <div className="mt-4 inline-flex items-center gap-1 text-[10px] text-slate-400 font-semibold uppercase font-mono tracking-wider">
                Read development specs <ArrowRight className="h-3 w-3" />
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
